quarkus.http.host=127.78.0.28
%dev.quarkus.http.host=localhost
quarkus.http.port=10000
quarkus.micrometer.export.prometheus.path=/metrics

# logging
%dev.quarkus.log.file.enable=false
%test.quarkus.log.file.enable=false
quarkus.log.file.enable=true
quarkus.log.file.async=true
quarkus.log.file.path=/var/log/carbonio/catalog/application.log

# consul
consul.url=http://localhost:8500
consul.token.filepath=/etc/carbonio/catalog/service-discover/token