# SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

---
openapi: 3.0.3
info:
  title: Carbonio Catalog API
  version: 1.0.0-BETA
servers:
- url: http://localhost:10000
- url: https://kc-dev1-prymta1.demo.zextras.io
- url: https://kc-dev2-prymta1.demo.zextras.io
- url: https://kc-dev3-prymta1.demo.zextras.io
tags:
- name: Health Resource
- name: Services Resource
paths:
  /health:
    get:
      tags:
      - Health Resource
      responses:
        "200":
          description: OK
  /health/live:
    get:
      tags:
      - Health Resource
      responses:
        "200":
          description: OK
  /health/ready:
    get:
      tags:
      - Health Resource
      responses:
        "200":
          description: OK
  /services:
    get:
      tags:
      - Services Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetServicesResponse"
components:
  schemas:
    GetServicesResponse:
      type: object
      properties:
        items:
          type: array
          items:
            type: string
