# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
# SPDX-License-Identifier: AGPL-3.0-only

# Create log directory for carbonio-catalog
d /var/log/carbonio/catalog 0755 carbonio-catalog carbonio-catalog -

# Set ownership on package-installed files
Z /usr/share/carbonio/carbonio-catalog 0755 carbonio-catalog carbonio-catalog -
